# Site settings
title: "Intuitív barangolások egy idealista tollából"
author: "Ejderha"
description: "Az itt megjelenő írások fő célja, a mai világunkban uralkodó materialista, fizikalista világnézet fölösleges szenvedtető uralmát megdönteni filozófiai alapokon és egy tágabb világnézet felé adni meghívást. Továbbá kötetlen intuitív felfedezése zajlik a létezésnek a lehető legtöbb szinten."
keywords: "Költészet, Filozófia, Idealizmus, Materializmus, Fizikalizmus, Nondualitás, Védikus, Zen, Tudat, Mesterséges Intelligencia, Halál, Isten"
biography: "A bölcsesség szerelmese vagyok, szégyentelen promiszkuitásban élek a világnézetemet tágító gondolatokkal."
colophon: 

baseurl: ""
url: "http://ejderhasite.github.io"

instagram_username: __ejderha
facebook_username: ejderha_poetry
google-analytics: UA-66666-6

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
